export const Background = () => (
  <svg
    width="100%"
    height="1033"
    viewBox="0 0 1280 1033"
    fill="none"
    xmlns="http://www.w3.org/2000/svg"
  >
    <g filter="url(#filter0_f_0_1)">
      <circle
        cx="111.5"
        cy="642.5"
        r="306.5"
        fill="#FF778F"
        fillOpacity="0.3"
      />
    </g>
    <g filter="url(#filter1_f_0_1)">
      <circle
        cx="1162.5"
        cy="110.5"
        r="229.5"
        fill="#00A07A"
        fillOpacity="0.3"
      />
    </g>
    <g filter="url(#filter2_f_0_1)">
      <circle
        cx="434.5"
        cy="-111.5"
        r="229.5"
        fill="#F4B000"
        fillOpacity="0.3"
      />
    </g>
    <g filter="url(#filter3_f_0_1)">
      <circle
        cx="1013.5"
        cy="1032.5"
        r="366.5"
        fill="#3F81FF"
        fillOpacity="0.3"
      />
    </g>
    <defs>
      <filter
        id="filter0_f_0_1"
        x="-595"
        y="-64"
        width="1413"
        height="1413"
        filterUnits="userSpaceOnUse"
        colorInterpolationFilters="sRGB"
      >
        <feFlood floodOpacity="0" result="BackgroundImageFix" />
        <feBlend
          mode="normal"
          in="SourceGraphic"
          in2="BackgroundImageFix"
          result="shape"
        />
        <feGaussianBlur
          stdDeviation="200"
          result="effect1_foregroundBlur_0_1"
        />
      </filter>
      <filter
        id="filter1_f_0_1"
        x="533"
        y="-519"
        width="1259"
        height="1259"
        filterUnits="userSpaceOnUse"
        colorInterpolationFilters="sRGB"
      >
        <feFlood floodOpacity="0" result="BackgroundImageFix" />
        <feBlend
          mode="normal"
          in="SourceGraphic"
          in2="BackgroundImageFix"
          result="shape"
        />
        <feGaussianBlur
          stdDeviation="200"
          result="effect1_foregroundBlur_0_1"
        />
      </filter>
      <filter
        id="filter2_f_0_1"
        x="-195"
        y="-741"
        width="1259"
        height="1259"
        filterUnits="userSpaceOnUse"
        colorInterpolationFilters="sRGB"
      >
        <feFlood floodOpacity="0" result="BackgroundImageFix" />
        <feBlend
          mode="normal"
          in="SourceGraphic"
          in2="BackgroundImageFix"
          result="shape"
        />
        <feGaussianBlur
          stdDeviation="200"
          result="effect1_foregroundBlur_0_1"
        />
      </filter>
      <filter
        id="filter3_f_0_1"
        x="247"
        y="266"
        width="1533"
        height="1533"
        filterUnits="userSpaceOnUse"
        colorInterpolationFilters="sRGB"
      >
        <feFlood floodOpacity="0" result="BackgroundImageFix" />
        <feBlend
          mode="normal"
          in="SourceGraphic"
          in2="BackgroundImageFix"
          result="shape"
        />
        <feGaussianBlur
          stdDeviation="200"
          result="effect1_foregroundBlur_0_1"
        />
      </filter>
    </defs>
  </svg>
);
